[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/About.py"
name = "About"
icon = "â„¹ï¸"

[[pages]]
path = "pages/Business_Chatbot.py"
name = "Business Chatbot"
icon = "ğŸ¤"

[[pages]]
path = "pages/Personal_Chatbot.py"
name = "Personal Chatbot"
icon = "ğŸ’›"

[[pages]]
path = "pages/Terms_and_Conditions.py"
name = "Terms and Conditions"
icon = "ğŸ“œ"
